# https://github.com/probot/settings

branches:
  - name: "master"

    # https://developer.github.com/v3/repos/branches/#remove-branch-protection
    # https://developer.github.com/v3/repos/branches/#update-branch-protection

    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - "Coding Standards (7.2, locked)"
          - "Dependency Analysis (7.4, locked)"
          - "Static Code Analysis (7.4, locked)"
          - "Tests (7.2, lowest)"
          - "Tests (7.2, locked)"
          - "Tests (7.2, highest)"
          - "Tests (7.3, lowest)"
          - "Tests (7.3, locked)"
          - "Tests (7.3, highest)"
          - "Tests (7.4, lowest)"
          - "Tests (7.4, locked)"
          - "Tests (7.4, highest)"
        strict: false
      restrictions:
        apps:
          - "dependabot-preview"
        teams: []
        users:
          - "ergebnis-bot"

# https://developer.github.com/v3/issues/labels/#create-a-label
# https://developer.github.com/v3/issues/labels/#update-a-label

labels:
  - name: "bug"
    color: "#ee0701"
    description: ""

  - name: "dependency"
    color: "#0366d6"
    description: ""

  - name: "enhancement"
    color: "#0e8a16"
    description: ""

  - name: "rfc"
    color: "#f4db3a"
    description: ""

  - name: "question"
    color: "#cc317c"
    description: ""

  - name: "security"
    color: "#ee0701"
    description: ""

  - name: "stale"
    color: "#eeeeee"
    description: ""

  - name: "vendor"
    color: "#f4db3a"
    description: ""

# https://developer.github.com/v3/repos/#edit

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: false
  default_branch: "master"
  delete_branch_on_merge: true
  description: ":grapes: Provides constants for HTTP request methods."
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: "http-method"
  private: false

  # https://developer.github.com/v3/repos/branches/#remove-branch-protection

  topics: "http, request, method"
