# https://github.com/actions/stale

name: "Prune"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 12 * * *"

jobs:
  prune:
    name: "Issues"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Prune issues and pull requests"
        uses: "actions/stale@v1"
        with:
          days-before-close: 5
          days-before-stale: 60
          repo-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          stale-issue-label: "stale"
          stale-issue-message: |
            Since this issue has not had any activity within the last sixty days, I have marked it as stale.

            I will close it if no further activity occurs within the next five days.
          stale-pr-label: "stale"
          stale-pr-message: |
            Since this pull request has not had any activity within the last sixty days, I have marked it as stale.

            I will close it if no further activity occurs within the next five days.
